[versions]
# project modules version
root = "1.0.0-dev"

# dependencies version
kotlin = "1.6.21"
spring-boot = "2.7.5"
qqrobot-spring-boot-starter = "1.3.4"
honoka-utils = "1.0.6"
lombok = "1.18.26"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
dependency-management = "io.spring.dependency-management:1.1.4"
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

[libraries]
qqrobot-spring-boot-starter = { module = "de.honoka.qqrobot:qqrobot-spring-boot-starter", version.ref = "qqrobot-spring-boot-starter" }
honoka-utils = { module = "de.honoka.sdk:honoka-utils", version.ref = "honoka-utils" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }